version: "3.8"

services:

  covid-user-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./userdatabase/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  keycloak:
    depends_on:
      - covid-user-db
    container_name: local_keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json

      DB_VENDOR: POSTGRES
      DB_ADDR: covid-user-db
      DB_DATABASE: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "28081:8080"
    volumes:
      - ./config/keycloak/realm-export.json:/tmp/realm-export.json

  api-gateway-service:
    image: apigatewayservice:0.0.1-SNAPSHOT
    ports:
      - "8090:8090"
    depends_on:
      - keycloak
    

  covid-location-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./userdatabase/init_location_fk.sql:/docker-entrypoint-initdb.d/init_location_fk.sql
    command: -p 6002

  user-service:
    image: userservice:0.0.1
    ports:
      - "5001:5001"
    depends_on:
    - keycloak

  discovery-service:
    image: discoveryserver:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
      

  location-service:
    image: location_service:0.0.1
    ports:
      - "3001:3001"
    depends_on:
      - covid-location-db

  config-server:
    image: configserver:0.0.1-SNAPSHOT
    ports:
      - "8888:8888"

  covid-vaccination-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./userdatabase/init_vaccination.sql:/docker-entrypoint-initdb.d/init_vaccination.sql
    command: -p 5433

  vaccination-service:
    image: vaccinationservice:0.0.1-SNAPSHOT
    ports:
      - "2001:2001"
    depends_on:
      - covid-vaccination-db

  notification-service:
    image: notificationservice:0.0.1-SNAPSHOT
    ports:
      - "7001:7001"
    depends_on:
      - kafka

  covid-test-db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./userdatabase/init_covidtest.sql:/docker-entrypoint-initdb.d/init_covidtest.sql
    command: -p 5434

  covidtest-service:
    image: covidtestservice:0.0.1-SNAPSHOT
    ports:
      - "1001:1001"
    depends_on:
      - covid-test-db

  news-service:
    image: newsservice:0.0.1-SNAPSHOT
    ports:
      - "4001:4001"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:1:3,PositiveUsersTopic:1:3,UserAlertTopic:1:3"



